/** Fatura de cartão: 3 débitos + 1 pagamento. Usada nos testes de parse e revisão. */
export const FIXTURE_FATURA_OFX = `OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:UTF-8
CHARSET:UTF-8

<OFX>
<CREDITCARDMSGSRSV1>
<CCSTMTTRNRS>
<CCSTMTRS>
<CURDEF>BRL
<BANKTRANLIST>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260815
<TRNAMT>-45.90
<FITID>FIT-IFOOD-1
<MEMO>IFOOD *PIZZA NAPOLI
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260818
<TRNAMT>-120,00
<FITID>FIT-SHELL-2
<NAME>POSTO SHELL CENTRO
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260820
<TRNAMT>-32.50
<FITID>FIT-LOJA-3
<MEMO>LOJA GENERICA XYZ
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260810
<TRNAMT>1500.00
<FITID>FIT-PAGTO-4
<MEMO>PAGAMENTO RECEBIDO
</STMTTRN>
</BANKTRANLIST>
</CCSTMTRS>
</CCSTMTTRNRS>
</CREDITCARDMSGSRSV1>
</OFX>
`;

/** Parcela 3/12 em 10/set — gera 10 lançamentos (3…12), sem 1 e 2. */
export const FIXTURE_PARCELA_OFX = `OFXHEADER:100
DATA:OFXSGML
VERSION:102

<OFX>
<CREDITCARDMSGSRSV1>
<CCSTMTTRNRS>
<CCSTMTRS>
<BANKTRANLIST>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260910
<TRNAMT>-250.00
<FITID>FIT-SOFA-3
<MEMO>MAGAZINE LUIZA PARC 3/12
</STMTTRN>
</BANKTRANLIST>
</CCSTMTRS>
</CCSTMTTRNRS>
</CREDITCARDMSGSRSV1>
</OFX>
`;

/** Cartão BR: compras como CREDIT; ajuste de crédito como o único “débito”. */
export const FIXTURE_NANQUIM_OFX = `OFXHEADER:100
DATA:OFXSGML
VERSION:102

<OFX>
<CREDITCARDMSGSRSV1>
<CCSTMTTRNRS>
<CCSTMTRS>
<BANKTRANLIST>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260805
<TRNAMT>35.00
<FITID>NAN-AGENOR
<MEMO>AGENOR LOGISTICA
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260805
<TRNAMT>105.00
<FITID>NAN-BARBA
<MEMO>BARBEARIADOKEL VIN
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260805
<TRNAMT>4.00
<FITID>NAN-PADARIA
<MEMO>DELICIAS DO PADEIRO C
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260817
<TRNAMT>9.00
<FITID>NAN-PARK
<MEMO>PARK EXPRESS
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260902
<TRNAMT>-0.04
<FITID>NAN-AJUSTE
<MEMO>AJUSTE CRED PARC S JUROS
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260810
<TRNAMT>800.00
<FITID>NAN-PGTO
<MEMO>PAGAMENTO RECEBIDO
</STMTTRN>
</BANKTRANLIST>
</CCSTMTRS>
</CCSTMTTRNRS>
</CREDITCARDMSGSRSV1>
</OFX>
`;

/** Extrato de conta corrente: débitos negativos + crédito positivo (sinal bancário). */
export const FIXTURE_CONTA_OFX = `OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:UTF-8
CHARSET:UTF-8

<OFX>
<BANKMSGSRSV1>
<STMTTRNRS>
<STMTRS>
<CURDEF>BRL
<BANKTRANLIST>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260812
<TRNAMT>-89.90
<FITID>CTA-IFOOD-1
<MEMO>IFOOD *BURGER HOUSE
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260814
<TRNAMT>-250,00
<FITID>CTA-ALUGUEL-2
<MEMO>ALUGUEL SETEMBRO
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260805
<TRNAMT>5200.00
<FITID>CTA-SALARIO-3
<MEMO>SALARIO EMPRESA XYZ
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260808
<TRNAMT>45.00
<FITID>CTA-ESTORNO-4
<MEMO>ESTORNO TAXA
</STMTTRN>
</BANKTRANLIST>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
`;
