/** Fatura de cartão: 3 débitos + 1 pagamento. Usada nos testes de parse e revisão. */
export const FIXTURE_FATURA_OFX = `OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:UTF-8
CHARSET:UTF-8

<OFX>
<CREDITCARDMSGSRSV1>
<CCSTMTTRNRS>
<CCSTMTRS>
<CURDEF>BRL
<BANKTRANLIST>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260815
<TRNAMT>-45.90
<FITID>FIT-IFOOD-1
<MEMO>IFOOD *PIZZA NAPOLI
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260818
<TRNAMT>-120,00
<FITID>FIT-SHELL-2
<NAME>POSTO SHELL CENTRO
</STMTTRN>
<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20260820
<TRNAMT>-32.50
<FITID>FIT-LOJA-3
<MEMO>LOJA GENERICA XYZ
</STMTTRN>
<STMTTRN>
<TRNTYPE>CREDIT
<DTPOSTED>20260810
<TRNAMT>1500.00
<FITID>FIT-PAGTO-4
<MEMO>PAGAMENTO RECEBIDO
</STMTTRN>
</BANKTRANLIST>
</CCSTMTRS>
</CCSTMTTRNRS>
</CREDITCARDMSGSRSV1>
</OFX>
`;
